### ISSUE TITLE
Leak Detection - New Leak - Bug

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#16]
When a new leak is created, if the user selects Submit without saving first, an error message is shown informing the user they must save first.  If the user clicks OK, then immediately on the save button, and then on the Submit button, the save action is not registered.  

In order to save, it appears that the user must first click somewhere on the screen and then click Save.

Please correct so that the user does not have to press Save twice, or have to press the screen then Save.

![image](https://cloud.githubusercontent.com/assets/7118831/2646643/1b66b3bc-bf41-11e3-92e3-30e2402be7e5.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
I'm still getting the error -- please revisit.

**Comment by kanglu666** [comment]
Clear your Browser cache

**Comment by alanfoster99** [comment]
Cache cleared -- error persists.  I see other changes which have posted -- please revisit.

**Comment by kanglu666** [comment]
tested, looks like it's Chrome browser issue, no error pup up.
Ipad works fine.

**Comment by alanfoster99** [comment]
Closing
